build-kernel: Shellcheck cleanup
Signed-off-by: Harsh Shandilya <msfjarvis@gmail.com>

diff --git a/build-kernel b/build-kernel
--- a/build-kernel
+++ b/build-kernel
@@ -13,21 +13,20 @@ if [[ -z ${KERNELDIR} ]]; then
     exit 1
 fi
 
-{ [[ "$(pwd)" =~ "whyred" ]] || [[ "$*" =~ "whyred" ]] ;} && DEVICE=whyred
-[[ -z "${DEVICE}" ]] && { [[ "$(pwd)" =~ "beryllium" ]] || [[ "$*" =~ "beryllium" ]] ;} && DEVICE=beryllium
+{ [[ "$(pwd)" =~ "whyred" ]] || [[ "$*" =~ "whyred" ]]; } && DEVICE=whyred
+[[ -z "${DEVICE}" ]] && { [[ "$(pwd)" =~ "beryllium" ]] || [[ "$*" =~ "beryllium" ]]; } && DEVICE=beryllium
 [[ -z "${DEVICE}" ]] && DEVICE=beryllium
 
 function tg() {
     case "${DEVICE}" in
-        "whyred")
-            sendKernelWhyred "${@:?}"
+    "whyred")
+        sendKernelWhyred "${@:?}"
         ;;
-        "beryllium")
-            sendKernelBeryllium "${@:?}"
+    "beryllium")
+        sendKernelBeryllium "${@:?}"
         ;;
     esac
 }
-
 
 # These won't change
 export SRCDIR="${KERNELDIR}/${DEVICE}"
@@ -56,20 +55,20 @@ export DEVICE CCACHE KBUILD_COMPILER_STRING JOBS CROSS_COMPILE
 function make_wrapper() {
     if [[ "${USE_GCC}" == "true" ]]; then
         time make -j"${JOBS}" \
-        O="${OUTDIR}" \
-        ARCH="${ARCH}" \
-        CROSS_COMPILE="${CCACHE} ${CROSS_COMPILE}" \
-        CROSS_COMPILE_ARM32="${CCACHE} ${CROSS_COMPILE_ARM32}" \
-        "${@}"
+            O="${OUTDIR}" \
+            ARCH="${ARCH}" \
+            CROSS_COMPILE="${CCACHE} ${CROSS_COMPILE}" \
+            CROSS_COMPILE_ARM32="${CCACHE} ${CROSS_COMPILE_ARM32}" \
+            "${@}"
     else
         time make -j"${JOBS}" \
-        O="${OUTDIR}" \
-        ARCH="${ARCH}" \
-        CC="${CCACHE} ${CC}" \
-        CLANG_TRIPLE="${CLANG_TRIPLE}" \
-        CROSS_COMPILE="${CROSS_COMPILE}" \
-        CROSS_COMPILE_ARM32="${CROSS_COMPILE_ARM32}" \
-        "${@}"
+            O="${OUTDIR}" \
+            ARCH="${ARCH}" \
+            CC="${CCACHE} ${CC}" \
+            CLANG_TRIPLE="${CLANG_TRIPLE}" \
+            CROSS_COMPILE="${CROSS_COMPILE}" \
+            CROSS_COMPILE_ARM32="${CROSS_COMPILE_ARM32}" \
+            "${@}"
     fi
 }
 
@@ -99,8 +98,8 @@ if [[ "$*" =~ "clean" ]]; then
     make_wrapper clean
 fi
 
-make_wrapper $DEFCONFIG || (echo "Failed to build with ${DEFCONFIG}, exiting!" && \
-		exit 1)
+make_wrapper $DEFCONFIG || (echo "Failed to build with ${DEFCONFIG}, exiting!" &&
+    exit 1)
 
 START=$(date +"%s")
 [[ "$*" =~ "upload" ]] && tg "Building!"
@@ -114,7 +113,6 @@ END=$(date +"%s")
 DIFF=$((END - START))
 echo -e "Build took $((DIFF / 60)) minute(s) and $((DIFF % 60)) seconds."
 [[ "$*" =~ "upload" ]] && tg "Build took $((DIFF / 60)) minute(s) and $((DIFF % 60)) seconds."
-
 
 if [[ ! -f "${IMAGE}" ]]; then
     echo -e "Build failed :P"
@@ -130,34 +128,33 @@ cp -v "${IMAGE}" "${ANYKERNEL}/"
 cd - || exit
 cd "${ANYKERNEL}" || exit
 zip -r9 "${FINAL_ZIP}" ./* -x ".git/*" "README.md" ".gitignore" "*.zip"
-md5sum "${FINAL_ZIP}" | sed -e "s|${ZIP_DIR}||" > "${FINAL_ZIP}.md5sum"
+md5sum "${FINAL_ZIP}" | sed -e "s|${ZIP_DIR}||" >"${FINAL_ZIP}.md5sum"
 cd - || exit
 
-if [ -f "$FINAL_ZIP" ]
-then
-echo -e "$NAME zip can be found at $FINAL_ZIP"
-if [[ "$*" =~ "transfer" ]]; then
-    echo -e "Uploading ${ZIPNAME} to https://transfer.sh/"
-    transfer "${FINAL_ZIP}"
-fi
-if [[ "$*" =~ "upload" ]]; then
-    echo -e "Uploading ${ZIPNAME}"
-    case $(hostname) in
-    "memebox")
-        rsync -av --progress --delete "${ZIP_DIR}"/* ~/mirror/kernel/${DEVICE}/Test/
-    ;;
-    "TheLab")
-        rsync -av --progress --delete "${ZIP_DIR}"/* /var/www/downloads.akhilnarang.me/kernel/${DEVICE}/Test/
-    ;;
-    *)
-        rsync -av --progress --delete "${ZIP_DIR}"/* akhil@ssh.packet.resurrectionremix.com:mirror/kernel/${DEVICE}/Test/
-    ;;
-    esac
-    mirrorsync
-    tg "Download ${ZIPNAME/\.zip/} from [here](${DOWNLOAD_BASE_URL}/${ZIPNAME})"
-fi
+if [ -f "$FINAL_ZIP" ]; then
+    echo -e "$NAME zip can be found at $FINAL_ZIP"
+    if [[ "$*" =~ "transfer" ]]; then
+        echo -e "Uploading ${ZIPNAME} to https://transfer.sh/"
+        transfer "${FINAL_ZIP}"
+    fi
+    if [[ "$*" =~ "upload" ]]; then
+        echo -e "Uploading ${ZIPNAME}"
+        case $(hostname) in
+        "memebox")
+            rsync -av --progress --delete "${ZIP_DIR}"/* ~/mirror/kernel/${DEVICE}/Test/
+            ;;
+        "TheLab")
+            rsync -av --progress --delete "${ZIP_DIR}"/* /var/www/downloads.akhilnarang.me/kernel/${DEVICE}/Test/
+            ;;
+        *)
+            rsync -av --progress --delete "${ZIP_DIR}"/* akhil@ssh.packet.resurrectionremix.com:mirror/kernel/${DEVICE}/Test/
+            ;;
+        esac
+        mirrorsync
+        tg "Download ${ZIPNAME/\.zip/} from [here](${DOWNLOAD_BASE_URL}/${ZIPNAME})"
+    fi
 else
-echo -e "Zip Creation Failed =("
+    echo -e "Zip Creation Failed =("
 fi # FINAL_ZIP check
 
 exit ${exitCode}
