scripts: stash miscellaneous cleanup
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>

diff --git a/build-kernel b/build-kernel
--- a/build-kernel
+++ b/build-kernel
@@ -6,11 +6,11 @@ source "${HOME}/scripts/startupstuff.sh";
 
 function check_toolchain() {
 
-    TC=$(find "${TOOLCHAIN}"/bin -type f -name "aarch64-*-gcc");
+    TC=$(find "${TOOLCHAIN}"/bin -type f -name "aarch64-*gnu-gcc");
 
 	if [[ -f "${TC}" ]]; then
-		CROSS_COMPILE="${CCACHE} ${TOOLCHAIN}/bin/$(echo ${TC} | awk -F '/' '{print $NF'} |\
-sed -e 's/gcc//')";
+		CROSS_COMPILE="${CCACHE} ${TOOLCHAIN}/bin/$(echo ${TC} | awk -F '/' \
+				'{print $NF'} | sed -e 's/gcc//')";
 		export CROSS_COMPILE;
 		echo -e "Using toolchain: $(${CROSS_COMPILE}gcc --version | head -1)";
 	else
@@ -40,6 +40,8 @@ export CCACHE="$(command -v ccache)";
 export DEFCONFIG="${DEVICE}_defconfig";
 export ZIP_DIR="${KERNELDIR}/files/${DEVICE}";
 export IMAGE="${OUTDIR}/arch/${ARCH}/boot/Image.gz-dtb";
+export DONWLOAD_BASE_URL_1="downloads.akhilnarang.me";
+export DOWNLOAD_BASE_URL_2="derpfest.msfjarvis.website";
 
 if [[ -z "${JOBS}" ]]; then
     JOBS="$(grep -c '^processor' /proc/cpuinfo)";
@@ -76,7 +78,8 @@ if [[ "$@" =~ "clean" ]]; then
     ${MAKE} clean
 fi
 
-${MAKE} $DEFCONFIG || (echo "Failed to build with ${DEFCONFIG}, exiting!" && exit 1);
+${MAKE} $DEFCONFIG || (echo "Failed to build with ${DEFCONFIG}, exiting!" && \
+		exit 1);
 
 START=$(date +"%s");
 ${MAKE} -j"${JOBS}";
@@ -119,11 +122,11 @@ if [[ "$@" =~ "upload" ]]; then
         scp "${ZIP_DIR}/${NAME}$f" "akhil@downloads.akhilnarang.me:downloads/kernel/oneplus3/Test/";
 		git -C ${SRCDIR} log akhilnarang/stable..HEAD > ${ZIP_DIR}/${NAME}-changelog.txt;
     done
-    ssh akhil@downloads.akhilnarang.me ~/gdrive sync upload downloads/kernel 1DnrCzSchI9MNHXkbiaqlw-qyRkNIDKFQ
-    GDRIVE_URL="https://drive.google.com/drive/folders/1PwLPGxfk0A1oj2nGATxdfYuguU7hZdJ4";
-    DOWNLOADS_URL="https://downloads.akhilnarang.me/kernel/oneplus3/Test";
+    ssh akhil@downloads.akhilnarang.me rsync -av --progress --delete kernel/ \
+    		${DOWNLOAD_BASE_URL_2}/nginx/kernel
+    MAIN_DOWNLOAD_URL="https://${DONWLOAD_BASE_URL_1}/kernel/oneplus3/Test";
+    MIRROR_DOWNLOAD_URL="https://${DONWLOAD_BASE_URL_2}/kernel/oneplus3/Test";
     bash ~/kronicbot/send_tg.sh "-1001122772970" "Check [Main]($DOWNLOADS_URL) | [Mirror]($GDRIVE_URL) for ${NAME}";
-    bash ~/kronicbot/send_tg.sh "-1001223901635" "Check [Main]($DOWNLOADS_URL) | [Mirror]($GDRIVE_URL) for ${NAME}";
 fi
 else
 echo -e "Zip Creation Failed =(";
diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -54,15 +54,17 @@ function repopick_stuff() {
 	export IFS=$oldifs;
 }
 
-# Creates a virtualenv and activates it
+# Creates a virtualenv if required and activates it
 function venv() {
-    PYV=$(python -c "import sys;t='{v[0]}'.format(v=list(sys.version_info[:1]));sys.stdout.write(t)");
+    PYV=$(python -c "import sys;t='{v[0]}'.format(v=list(sys.version_info[:1]))\
+            ;sys.stdout.write(t)");
     if [[ "${PYV}" == "3" ]]; then
         if [[ "$(command -v 'virtualenv2')" ]]; then
             virtualenv2 /tmp/venv;
             source /tmp/venv/bin/activate;
         else
-            echo "Please install 'virtualenv2', or make 'python' point to python2";
+            echo "Please install 'virtualenv2', or make 'python' point to \
+                    python2";
         fi
     fi
 }
@@ -85,7 +87,7 @@ function transfer() {
     echo -e "Download $zipname at $url";
 }
 
-# Creates a virtualenv if required, runs the given command, and then deactivates it
+# Calls venv(), runs the given command, and then calls rmvenv()
 function run_virtualenv() {
 	venv
 
@@ -94,11 +96,13 @@ function run_virtualenv() {
     rmvenv;
 }
 
-# Function to repo sync with a lot of flags because I'm lazy to type them over and and over again
+# Repo sync with various flags I'm lazy to type each time
 function syncc() {
-    time run_virtualenv repo sync --force-broken --force-sync --no-clone-bundle --current-branch --no-tags "$@";
+    time run_virtualenv repo sync --force-broken --force-sync --no-clone-bundle\
+             --current-branch --no-tags "$@";
 }
 
+# Some git aliases for an easier workflow
 function gitalias() {
 	git config --global alias.s 'status';
 	git config --global alias.p 'push';
@@ -124,4 +128,28 @@ function gitalias() {
 	git config --global alias.cs 'commit --signoff';
 	git config --global alias.ca 'commit --amend';
 	git config --global alias.gerrit 'push gerrit HEAD:refs/for/oreo-mr1';
+}
+
+# Sends messages to Telegram to a specified chat via the desired bot
+function sendTG() {
+    bot=${1};
+    shift;
+    chat=${1};
+    shift;
+
+    case ${bot} in
+        "ts")
+            BOT_API_KEY="$(cat ~/.tskey)";
+        ;;
+        "kronic")
+            BOT_API_KEY="$(cat ~/.kronickey)";
+        ;;
+        "rr")
+            BOT_API_KEY="$(cat ~/.rrkey)";
+        ;;
+        *)
+            echo -e "Invalid bot, must be one of ts|kronic|rr!";
+            exit 1;
+        ;;
+    esac
 }
