scripts: sed -i -e 's/;$//g' -e 's/;$/;;/g' on all files
  Remove all semicolons that are there just because but aren't needed

  Also make kernel release script functional

Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>

diff --git a/build-kernel b/build-kernel
--- a/build-kernel
+++ b/build-kernel
@@ -4,61 +4,61 @@
 # SPDX-License-Identifier: GPL-3.0-only
 # Kernel build script
 
-source "${HOME}/scripts/functions";
+source "${HOME}/scripts/functions"
 
 if [[ -z ${KERNELDIR} ]]; then
-    echo -e "Please set KERNELDIR";
-    exit 1;
+    echo -e "Please set KERNELDIR"
+    exit 1
 fi
 
-export DEVICE=whyred;
+export DEVICE=whyred
 #if [[ -z ${DEVICE} ]]; then
-#    export DEVICE="whyred";
+#    export DEVICE="whyred"
 #fi
 
 # These won't change
-export SRCDIR="${KERNELDIR}/${DEVICE}";
-export OUTDIR="${KERNELDIR}/${DEVICE}/obj";
-export ANYKERNEL="${KERNELDIR}/anykernel/${DEVICE}";
-export MODULES_DIR="${ANYKERNEL}/modules/vendor/lib/modules";
-export ARCH="arm64";
-export CCACHE="$(command -v ccache)";
-export CLANG_DIR="${HOME}/clang-build/build";
-export GCC_DIR="${HOME}/build-tools-gcc/aarch64-linux-gnu";
-export CROSS_COMPILE="${GCC_DIR}/bin/aarch64-linux-gnu-";
-export CLANG_TRIPLE="aarch64-linux-gnu-";
-export CC="${CLANG_DIR}/bin/clang";
+export SRCDIR="${KERNELDIR}/${DEVICE}"
+export OUTDIR="${KERNELDIR}/${DEVICE}/obj"
+export ANYKERNEL="${KERNELDIR}/anykernel/${DEVICE}"
+export MODULES_DIR="${ANYKERNEL}/modules/vendor/lib/modules"
+export ARCH="arm64"
+export CCACHE="$(command -v ccache)"
+export CLANG_DIR="${HOME}/clang-build/build"
+export GCC_DIR="${HOME}/build-tools-gcc/aarch64-linux-gnu"
+export CROSS_COMPILE="${GCC_DIR}/bin/aarch64-linux-gnu-"
+export CLANG_TRIPLE="aarch64-linux-gnu-"
+export CC="${CLANG_DIR}/bin/clang"
 export KBUILD_COMPILER_STRING=$(${CC} --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')
-export DEFCONFIG="${DEVICE}_defconfig";
-export ZIP_DIR="${KERNELDIR}/files/${DEVICE}";
-export IMAGE="${OUTDIR}/arch/${ARCH}/boot/Image.gz-dtb";
-export DOWNLOAD_BASE_URL_1="https://downloads.akhilnarang.me/kernel/${DEVICE}/Test/";
-export DOWNLOAD_BASE_URL_2="https://mirror.akhilnarang.me/kernel/${DEVICE}/Test/";
+export DEFCONFIG="${DEVICE}_defconfig"
+export ZIP_DIR="${KERNELDIR}/files/${DEVICE}"
+export IMAGE="${OUTDIR}/arch/${ARCH}/boot/Image.gz-dtb"
+export DOWNLOAD_BASE_URL_1="https://downloads.akhilnarang.me/kernel/${DEVICE}/Test/"
+export DOWNLOAD_BASE_URL_2="https://mirror.akhilnarang.me/kernel/${DEVICE}/Test/"
 
 if [[ -z "${JOBS}" ]]; then
-    JOBS="$(grep -c '^processor' /proc/cpuinfo)";
-    export JOBS;
+    JOBS="$(grep -c '^processor' /proc/cpuinfo)"
+    export JOBS
 fi
 
 if [[ ! -d "${ANYKERNEL}" ]]; then
-    git clone AnyKernel2 -b "${DEVICE}" "${ANYKERNEL}";
+    git clone AnyKernel2 -b "${DEVICE}" "${ANYKERNEL}"
 fi
 
-export MAKE="make O=${OUTDIR}";
+export MAKE="make O=${OUTDIR}"
 
 if [[ -z "${NAME}" ]]; then
-    export NAME="derp";
+    export NAME="derp"
 fi
-NAME="${NAME}-${DEVICE}-$(date +%Y%m%d-%H%M)";
-export NAME;
+NAME="${NAME}-${DEVICE}-$(date +%Y%m%d-%H%M)"
+export NAME
 export ZIPNAME="${NAME}.zip"
 export FINAL_ZIP="${ZIP_DIR}/${ZIPNAME}"
 
 [ ! -d "${ZIP_DIR}" ] && mkdir -pv "${ZIP_DIR}"
 [ ! -d "${OUTDIR}" ] && mkdir -pv "${OUTDIR}"
 
-cd "${SRCDIR}" || exit;
-rm -fv "${IMAGE}";
+cd "${SRCDIR}" || exit
+rm -fv "${IMAGE}"
 
 if [[ "$@" =~ "mrproper" ]]; then
     ${MAKE} mrproper
@@ -69,59 +69,59 @@ if [[ "$@" =~ "clean" ]]; then
 fi
 
 ${MAKE} $DEFCONFIG || (echo "Failed to build with ${DEFCONFIG}, exiting!" && \
-		exit 1);
+		exit 1)
 
-START=$(date +"%s");
-sendTG kronic derp md "Building!";
+START=$(date +"%s")
+sendTG kronic derp md "Building!"
 if [[ "$@" =~ "quiet" ]]; then
     ${MAKE} -j"${JOBS}" CC="$(command -v ccache) ${CC}" CLANG_TRIPLE="${CLANG_TRIPLE}" |& ag -ia "error:|warning:"
 else
-    ${MAKE} -j"${JOBS}" CC="$(command -v ccache) ${CC}" CLANG_TRIPLE="${CLANG_TRIPLE}";
+    ${MAKE} -j"${JOBS}" CC="$(command -v ccache) ${CC}" CLANG_TRIPLE="${CLANG_TRIPLE}"
 fi
-exitCode="$?";
+exitCode="$?"
 END=$(date +"%s")
 DIFF=$((END - START))
-echo -e "Build took $((DIFF / 60)) minute(s) and $((DIFF % 60)) seconds.";
+echo -e "Build took $((DIFF / 60)) minute(s) and $((DIFF % 60)) seconds."
 
 if [[ ! -f "${IMAGE}" ]]; then
-    echo -e "Build failed :P";
-    sendTG kronic derp md "Build failed!";
-    exit 1;
+    echo -e "Build failed :P"
+    sendTG kronic derp md "Build failed!"
+    exit 1
 else
-    echo -e "Build Succesful!";
+    echo -e "Build Succesful!"
 fi
 
-echo -e "Copying kernel image";
-cp -v "${IMAGE}" "${ANYKERNEL}/";
+echo -e "Copying kernel image"
+cp -v "${IMAGE}" "${ANYKERNEL}/"
 
-grep -q "=m" ${OUTDIR}/.config;
+grep -q "=m" ${OUTDIR}/.config
 if [[ "$?" -eq 0 ]]; then
-    find ${OUTDIR} -name "*.ko" -exec cp -v {} ${MODULES_DIR} \;
+    find ${OUTDIR} -name "*.ko" -exec cp -v {} ${MODULES_DIR} \
     for module in $(ls ${MODULES_DIR/*.ko}); do
-  		${CROSS_COMPILE}strip --strip-unneeded "${MODULES_DIR}/${module}";
+  		${CROSS_COMPILE}strip --strip-unneeded "${MODULES_DIR}/${module}"
   	done
 fi # Modules check
-cd - || exit;
-cd "${ANYKERNEL}" || exit;
-zip -r9 "${FINAL_ZIP}" *;
-md5sum ${FINAL_ZIP} | sed -e "s|${ZIP_DIR}||" > ${FINAL_ZIP}.md5sum;
-cd - || exit;
+cd - || exit
+cd "${ANYKERNEL}" || exit
+zip -r9 "${FINAL_ZIP}" *
+md5sum ${FINAL_ZIP} | sed -e "s|${ZIP_DIR}||" > ${FINAL_ZIP}.md5sum
+cd - || exit
 
-if [ -f "$FINAL_ZIP" ];
+if [ -f "$FINAL_ZIP" ]
 then
-echo -e "$NAME zip can be found at $FINAL_ZIP";
+echo -e "$NAME zip can be found at $FINAL_ZIP"
 if [[ "$@" =~ "transfer" ]]; then
-    echo -e "Uploading ${ZIPNAME} to https://transfer.sh/";
-    transfer "${FINAL_ZIP}";
+    echo -e "Uploading ${ZIPNAME} to https://transfer.sh/"
+    transfer "${FINAL_ZIP}"
 fi
 if [[ "$@" =~ "upload" ]]; then
-    echo -e "Uploading ${ZIPNAME}";
-    rsync -av --progress --delete ${ZIP_DIR}/* akhil@downloads.akhilnarang.me:/var/www/downloads.akhilnarang.me/kernel/${DEVICE}/Test/;
-    rsync -av --progress --delete ${ZIP_DIR}/* akhil@mirror.akhilnarang.me:/var/www/mirror.akhilnarang.me/kernel/${DEVICE}/Test/;
-    sendTG kronic derp md "Download ${ZIPNAME} from [Main](${DOWNLOAD_BASE_URL_1}) | [Mirror](${DOWNLOAD_BASE_URL_2})";
+    echo -e "Uploading ${ZIPNAME}"
+    rsync -av --progress --delete ${ZIP_DIR}/* akhil@downloads.akhilnarang.me:/var/www/downloads.akhilnarang.me/kernel/${DEVICE}/Test/
+    rsync -av --progress --delete ${ZIP_DIR}/* akhil@mirror.akhilnarang.me:/var/www/mirror.akhilnarang.me/kernel/${DEVICE}/Test/
+    sendTG kronic derp md "Download ${ZIPNAME} from [Main](${DOWNLOAD_BASE_URL_1}) | [Mirror](${DOWNLOAD_BASE_URL_2})"
 fi
 else
-echo -e "Zip Creation Failed =(";
+echo -e "Zip Creation Failed =("
 fi # FINAL_ZIP check
 
-exit ${exitCode};
+exit ${exitCode}
diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -5,14 +5,14 @@
 
 # Script defining various functions used in the scripts across this repository
 
-source ~/scripts/aliases;
+source ~/scripts/aliases
 
 # Builds a package from the Arch User Repository
 function aur() {
-	git clone https://aur.archlinux.org/$1;
-	cd $1;
-	makepkg -si $2;
-	cd -;
+	git clone https://aur.archlinux.org/$1
+	cd $1
+	makepkg -si $2
+	cd -
 }
 
 # FORMATS THE TIME
@@ -51,27 +51,27 @@ function format_time() {
 
 # Repopicks a | delimited set of commits
 function repopick_stuff() {
-	export oldifs=$IFS;
-	export IFS="|";
+	export oldifs=$IFS
+	export IFS="|"
 	for f in ${REPOPICK_LIST}; do
-	    echo $f;
-	    repopick $f;
-	    [[ $? -ne 0 ]] && exit 1;
+	    echo $f
+	    repopick $f
+	    [[ $? -ne 0 ]] && exit 1
 	done
-	export IFS=$oldifs;
+	export IFS=$oldifs
 }
 
 # Creates a virtualenv if required and activates it
 function venv() {
     PYV=$(python -c "import sys;t='{v[0]}'.format(v=list(sys.version_info[:1]))\
-            ;sys.stdout.write(t)");
+            ;sys.stdout.write(t)")
     if [[ "${PYV}" == "3" ]]; then
         if [[ "$(command -v 'virtualenv2')" ]]; then
-            virtualenv2 /tmp/venv;
-            source /tmp/venv/bin/activate;
+            virtualenv2 /tmp/venv
+            source /tmp/venv/bin/activate
         else
             echo "Please install 'virtualenv2', or make 'python' point to \
-                    python2";
+                    python2"
         fi
     fi
 }
@@ -79,154 +79,154 @@ function venv() {
 # Deactivates a virtualenv and deletes the folder
 function rmvenv() {
     if [[ -d "/tmp/venv/" ]]; then
-        deactivate;
-        rm -rf /tmp/venv/bin/activate;
+        deactivate
+        rm -rf /tmp/venv/bin/activate
     fi
 }
 
 # Uploads a given file to transfer.sh
 function transfer() {
-    file="$1";
+    file="$1"
     zipname=$(echo "${file}" | awk -F '/' '{print $NF}')
-    destination="$2";
-    url=$(curl -# -T "${file}" https://transfer.sh/${destination});
-    printf '\n';
-    echo -e "Download $zipname at $url";
+    destination="$2"
+    url=$(curl -# -T "${file}" https://transfer.sh/${destination})
+    printf '\n'
+    echo -e "Download $zipname at $url"
 }
 
 # Calls venv(), runs the given command, and then calls rmvenv()
 function run_virtualenv() {
 	venv
 
-    "$@";
+    "$@"
 
-    rmvenv;
+    rmvenv
 }
 
 # Repo sync with various flags I'm lazy to type each time
 function syncc() {
     time run_virtualenv repo sync --force-broken --force-sync --no-clone-bundle\
-             --current-branch --no-tags "$@";
+             --current-branch --no-tags "$@"
 }
 
 # Some git aliases for an easier workflow
 function gitalias() {
-	git config --global alias.s 'status';
-	git config --global alias.p 'push';
-	git config --global alias.pl 'pull';
-	git config --global alias.f 'fetch';
-	git config --global alias.r 'remote';
-	git config --global alias.rv 'remote --verbose';
-	git config --global alias.rev 'revert';
-	git config --global alias.re 'reset';
-	git config --global alias.cp 'cherry-pick';
-	git config --global alias.cpc 'cherry-pick --continue';
-	git config --global alias.cpa 'cherry-pick --abort';
-	git config --global alias.rh 'reset --hard';
-	git config --global alias.rs 'reset --soft';
-	git config --global alias.rb 'rebase';
-	git config --global alias.rbi 'rebase --interactive';
-	git config --global alias.rbc 'rebase --continue';
-	git config --global alias.rba 'rebase --abort';
-	git config --global alias.rbs 'rebase --skip';
-	git config --global alias.d 'diff';
-	git config --global alias.dc 'diff --cached';
-	git config --global alias.b 'bisect';
-	git config --global alias.c 'commit';
-	git config --global alias.cs 'commit --signoff';
-	git config --global alias.ca 'commit --amend';
-	git config --global alias.cn 'commit --no-edit';
-	git config --global alias.gerrit 'push gerrit HEAD:refs/for/oreo-mr1';
-	git config --global alias.add-change-id "!EDITOR='sed -i -re s/^pick/e/' sh -c 'git rebase -i $1 && while test -f .git/rebase-merge/interactive; do git commit --amend --no-edit && git rebase --continue; done' -";
+	git config --global alias.s 'status'
+	git config --global alias.p 'push'
+	git config --global alias.pl 'pull'
+	git config --global alias.f 'fetch'
+	git config --global alias.r 'remote'
+	git config --global alias.rv 'remote --verbose'
+	git config --global alias.rev 'revert'
+	git config --global alias.re 'reset'
+	git config --global alias.cp 'cherry-pick'
+	git config --global alias.cpc 'cherry-pick --continue'
+	git config --global alias.cpa 'cherry-pick --abort'
+	git config --global alias.rh 'reset --hard'
+	git config --global alias.rs 'reset --soft'
+	git config --global alias.rb 'rebase'
+	git config --global alias.rbi 'rebase --interactive'
+	git config --global alias.rbc 'rebase --continue'
+	git config --global alias.rba 'rebase --abort'
+	git config --global alias.rbs 'rebase --skip'
+	git config --global alias.d 'diff'
+	git config --global alias.dc 'diff --cached'
+	git config --global alias.b 'bisect'
+	git config --global alias.c 'commit'
+	git config --global alias.cs 'commit --signoff'
+	git config --global alias.ca 'commit --amend'
+	git config --global alias.cn 'commit --no-edit'
+	git config --global alias.gerrit 'push gerrit HEAD:refs/for/oreo-mr1'
+	git config --global alias.add-change-id "!EDITOR='sed -i -re s/^pick/e/' sh -c 'git rebase -i $1 && while test -f .git/rebase-merge/interactive; do git commit --amend --no-edit && git rebase --continue; done' -"
 }
 
 # Function to display uptime of a system. All credits to the original author.
 function upinfo() {
-    echo -ne "${green}$(hostname) ${red}uptime is ${cyan} \\t ";uptime | awk /'up/ {print $3,$4,$5,$6,$7,$8,$9,$10,$11}';
+    echo -ne "${green}$(hostname) ${red}uptime is ${cyan} \\t ";uptime | awk /'up/ {print $3,$4,$5,$6,$7,$8,$9,$10,$11}'
 }
 
 # Function run on login to display some stuff and set my custom PS1
 function onLogin() {
-    export GIT_PS1_SHOWDIRTYSTATE=1;
-    export GIT_PS1_SHOWSTASHSTATE=1;
-    export GIT_PS1_SHOWUNTRACKEDFILES=1;
-    export GIT_PS1_SHOWUPSTREAM=auto;
-    export GIT_PS1_SHOWCOLORHINTS=1;
-    unset PS1;
-    #PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ ';
+    export GIT_PS1_SHOWDIRTYSTATE=1
+    export GIT_PS1_SHOWSTASHSTATE=1
+    export GIT_PS1_SHOWUNTRACKEDFILES=1
+    export GIT_PS1_SHOWUPSTREAM=auto
+    export GIT_PS1_SHOWCOLORHINTS=1
+    unset PS1
+    #PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '
     if [[ -f "${HOME}/git-prompt.sh" ]]; then
         source ~/git-prompt.sh
-        PS1='| \h (\w)$(__git_ps1 " {%s}") |-> ';
+        PS1='| \h (\w)$(__git_ps1 " {%s}") |-> '
     else
-        PS1='| \h (\w) |-> ';
+        PS1='| \h (\w) |-> '
     fi
-    clear;
-    HOST=$(hostname);
+    clear
+    HOST=$(hostname)
     if [[ ${#HOST} -lt 14 ]]; then
-        echo -e "${lightgray}";figlet -c "$(hostname)";
+        echo -e "${lightgray}";figlet -c "$(hostname)"
     fi
     echo ""
-    echo -ne "${red}Today is:\\t\\t${cyan} $(date)";
+    echo -ne "${red}Today is:\\t\\t${cyan} $(date)"
     echo ""
     echo -e "${red}Kernel Information: \\t${cyan} $(uname -smr)"
-    echo -ne "${cyan}";
-    upinfo;
-    echo "";
-    echo -e "Welcome to $(hostname), $(whoami)!";
-    echo -e;
-    fortune;
+    echo -ne "${cyan}"
+    upinfo
+    echo ""
+    echo -e "Welcome to $(hostname), $(whoami)!"
+    echo -e
+    fortune
 }
 
 # Sends messages to Telegram to a specified chat via the desired bot
 function sendTG() {
-    bot=${1};
-    shift;
-    chat=${1};
-    shift;
-    parse_mode=${1};
-    shift;
+    bot=${1}
+    shift
+    chat=${1}
+    shift
+    parse_mode=${1}
+    shift
     case ${bot} in
         "ts")
-            BOT_API_KEY="$(cat ~/.tskey)";
+            BOT_API_KEY="$(cat ~/.tskey)"
         ;;
         "kronic")
-            BOT_API_KEY="$(cat ~/.kronickey)";
+            BOT_API_KEY="$(cat ~/.kronickey)"
         ;;
         "rr")
-            BOT_API_KEY="$(cat ~/.rrkey)";
+            BOT_API_KEY="$(cat ~/.rrkey)"
         ;;
         *)
-            echo -e "Invalid bot, must be one of ts|kronic|rr!";
-            return;
+            echo -e "Invalid bot, must be one of ts|kronic|rr!"
+            return
         ;;
     esac
 
     case ${chat} in
         "me")
-            CHAT_ID="92027269";
+            CHAT_ID="92027269"
         ;;
         "derp")
-            CHAT_ID="-1001313293729";
+            CHAT_ID="-1001313293729"
         ;;
         *)
-            echo -e "Invalid chat, must be one of me|derp!";
-            return;
+            echo -e "Invalid chat, must be one of me|derp!"
+            return
         ;;
     esac
 
     case ${parse_mode} in
         "markdown"|"Markdown"|"md")
-            export parse_mode="Markdown";
+            export parse_mode="Markdown"
         ;;
         "Html"|"html"|"HTML")
-            export parse_mode="HTML";
+            export parse_mode="HTML"
         ;;
         *)
-            echo -e "Invalid parse mode, must be one of Markdown|HTML!";
-            return;
+            echo -e "Invalid parse mode, must be one of Markdown|HTML!"
+            return
         ;;
     esac
 
-    curl -s "https://api.telegram.org/bot${BOT_API_KEY}/sendMessage" --data "text=${@}&chat_id=${CHAT_ID}&parse_mode=${parse_mode}" 1>/dev/null;
-    echo;
+    curl -s "https://api.telegram.org/bot${BOT_API_KEY}/sendMessage" --data "text=${@}&chat_id=${CHAT_ID}&parse_mode=${parse_mode}" 1>/dev/null
+    echo
 }
diff --git a/rom b/rom
--- a/rom
+++ b/rom
@@ -3,86 +3,86 @@
 # Build script to compile Android ROMs
 
 function sendHelp() {
-	echo -e "Usage";
+	echo -e "Usage"
 	echo -e "bash $0 <rom> -d <device> [NEEDED] [ROM can be aosip|caf|rr, device oneplus3|kenzo]"
-	echo -e "Optional flags: <sync|nosync> <clean|noclean> <user|userdebug|eng> <rmccache> <-j X|--jobs X> <bootimage|recoveryimage>";
-    exit 1;
+	echo -e "Optional flags: <sync|nosync> <clean|noclean> <user|userdebug|eng> <rmccache> <-j X|--jobs X> <bootimage|recoveryimage>"
+    exit 1
 }
 
 function rr() {
-	export LUNCH="rr";
+	export LUNCH="rr"
 	if [[ -z "${RR_BUILDTYPE}" ]]; then
-		export RR_BUILDTYPE="Experimental";
+		export RR_BUILDTYPE="Experimental"
 	fi
 	if [[ -z "${days_to_log}" ]]; then
-		export days_to_log="0";
+		export days_to_log="0"
 	fi
-	export ZIPNAME="RR-O";
+	export ZIPNAME="RR-O"
 }
 
 function caf() {
-	export LUNCH="aosp";
-	export ZIPNAME="aosp-caf";
+	export LUNCH="aosp"
+	export ZIPNAME="aosp-caf"
 }
 
 function aosip() {
-	export LUNCH="aosip";
+	export LUNCH="aosip"
 	if [[ -z "${AOSIP_BUILDTYPE}" ]]; then
-		export AOSIP_BUILDTYPE="DerpFest";
+		export AOSIP_BUILDTYPE="DerpFest"
 	fi
-	export ZIPNAME="AOSiP";
+	export ZIPNAME="AOSiP"
 	export MAKE="kronic"
 }
 
 while [[ $# -gt 0 ]]; do
 	case "$1" in
 		"aosip"|"caf"|"rr")
-			ROM="$1";
-			echo -e "ROM: ${ROM}";
+			ROM="$1"
+			echo -e "ROM: ${ROM}"
 			;;
 		"-d"|"--device")
-			shift;
+			shift
 			if [[ "$#" -gt 0 ]]; then
-				DEVICE="$1";
+				DEVICE="$1"
 			else
-				echo -e "Please specify device!";
-				exit 1;
+				echo -e "Please specify device!"
+				exit 1
 			fi
-			echo -e "DEVICE: ${DEVICE}";
+			echo -e "DEVICE: ${DEVICE}"
 			;;
 		"sync"|"nosync")
-			SYNC="$1";
-			echo -e "SYNC: ${SYNC}";
+			SYNC="$1"
+			echo -e "SYNC: ${SYNC}"
 			;;
 		"clean"|"noclean")
-			CLEAN="$1";
-			echo -e "CLEAN: ${CLEAN}";
+			CLEAN="$1"
+			echo -e "CLEAN: ${CLEAN}"
 			;;
 		"user"|"userdebug"|"eng")
-			VARIANT="$1";
-			echo -e "VARIANT: ${VARIANT}";
+			VARIANT="$1"
+			echo -e "VARIANT: ${VARIANT}"
 			;;
 		"rmccache")
-			NUKECCACHE="true";
+			NUKECCACHE="true"
 			;;
 		"-j"|"--jobs")
-			shift;
+			shift
 			if [[ $# -gt 0 ]]; then
-				JOBS="$1";
+				JOBS="$1"
 			else
-				echo -e "Please specify as value for jobs";
-				exit 1;
+				echo -e "Please specify as value for jobs"
+				exit 1
 			fi
 			;;
                 "bootimage"|"recoveryimage")
-                        TARGET="$1";
+                        TARGET="$1"
                         ;;
 		"-h"|"--help")
-			sendHelp;
+			sendHelp
 			;;
 		*)
-			echo -e "Invalid input!";
-			sendHelp;
+			echo -e "Invalid input!"
+			sendHelp
 			;;
 	esac
 	shift
@@ -92,34 +92,34 @@ done
 [[ -z "${ROM}" ]] && ROM="aosip"
 [[ -z "${VARIANT}" ]] && VARIANT="userdebug"
 
-${ROM};
+${ROM}
 
-ROM_SOURCE_DIR="${HOME}/${DIR}";
+ROM_SOURCE_DIR="${HOME}/${DIR}"
 
 if [[ ! -d "${ROM_SOURCE_DIR}" ]]; then
-	echo -e "${ROM_SOURCE_DIR} dosen't exist, please sync up in the correct folder and rerun";
-	exit 1;
+	echo -e "${ROM_SOURCE_DIR} dosen't exist, please sync up in the correct folder and rerun"
+	exit 1
 fi
 
-cd "${ROM_SOURCE_DIR}";
+cd "${ROM_SOURCE_DIR}"
 
 if [[ ! -d ".repo" ]]; then
-	echo -e ".repo folder not found - not in a properly synced android tree - please sync properly";
-	exit 1;
+	echo -e ".repo folder not found - not in a properly synced android tree - please sync properly"
+	exit 1
 fi
 
-venv;
+venv
 
-source build/envsetup.sh;
+source build/envsetup.sh
 
 lunch "${LUNCH}_${DEVICE}-${VARIANT}"
 
 if [[ "${CLEAN}" == "clean" ]]; then
-	make clobber;
+	make clobber
 fi
 
 if [[ "${NUKECCACHE}" == "true" ]]; then
-        ccache -C;
+        ccache -C
 fi
 
 if [[ -z "${MAKE}" ]]; then
@@ -131,54 +131,54 @@ if [[ -z "${MAKE}" ]]; then
 fi
 
 if [[ -z "${TARGET}" ]]; then
-    TARGET="${MAKE}";
+    TARGET="${MAKE}"
 fi
 
 if [[ -z "${JOBS}" ]];then
-	JOBS="$(nproc)";
+	JOBS="$(nproc)"
 fi
 
-export USE_CCACHE=1;
-export CCACHE_DIR="${HOME}/.ccache";
-ccache -M 200;
+export USE_CCACHE=1
+export CCACHE_DIR="${HOME}/.ccache"
+ccache -M 200
 
 if [[ "${SYNC}" == "sync" ]]; then
     syncc -j${JOBS}
 fi
 
 if [[ "$(command -v 'mka')" ]]; then
-	MAKE="mka ${TARGET}";
+	MAKE="mka ${TARGET}"
 else
-	MAKE="make -j${JOBS} ${TARGET}";
+	MAKE="make -j${JOBS} ${TARGET}"
 fi
 
 LOG="${HOME}/logs/${ROM}_${DEVICE}_$(date +%Y%m%d-%H%M).log"
 
-START="$(date +%s)";
+START="$(date +%s)"
 eval "${MAKE}" 2>&1 | tee ${LOG}
-END="$(date +%s)";
+END="$(date +%s)"
 
-format_time ${END} ${START};
+format_time ${END} ${START}
 
 
 if [[ "${TARGET}" == "bootimage" ]]; then
-    OUTPUT="boot.img";
+    OUTPUT="boot.img"
 elif [[ "{TARGET"} == "recoveryimage" ]]; then
-    OUTPUT="recovery.img";
+    OUTPUT="recovery.img"
 else
-    OUTPUT="${ZIPNAME}";
+    OUTPUT="${ZIPNAME}"
 fi
 
 if [[ "$(ls ${OUT}/${OUTPUT}*)" ]]; then
-	echo -e "Build succeeded";
+	echo -e "Build succeeded"
 else
-	echo -e "Build failed, check ${LOG}";
+	echo -e "Build failed, check ${LOG}"
 fi
 
 
 if [[ -d "/tmp/venv" ]]; then
-    rmvenv;
+    rmvenv
 fi
 
-echo -e "Stopping jack server";
-./prebuilts/sdk/tools/jack-admin stop-server;
+echo -e "Stopping jack server"
+./prebuilts/sdk/tools/jack-admin stop-server
